
markdown:            kramdown
highlighter:         rouge


# Permalinks
permalink: pretty
# relative_permalinks: true

# Setup
title:               'Tech Links'
tagline:             'Recent interesting articles and findings'
description:         'My Tech findings.'
url:                 http://techlinks.tsugliani.fr/
baseurl:             ''
paginate:            10

# About/contact
author:
  name:              Timo Sugliani
  url:               https://twitter.com/tsugliani
  email:             timo.sugliani@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
