# Display
markdown:           kramdown
highlighter:        rouge

# Permalinks
permalink:          pretty

# Setup
title:              'Tech Links'
tagline:            'Recent findings & interesting articles'
description:        'Passionate Technologist sharing his findings with the community'
url:                http://techlinks.tsugliani.fr/
baseurl:            ''
paginate:           10

# About/contact
author:
  name:             Timo Sugliani
  url:              https://twitter.com/tsugliani
  email:            timo.sugliani@gmail.com

# Custom vars
version:            1.0.0

# Dependencies
gems:               [jekyll-paginate]
